### ISSUE TITLE
Authorization is required to perform that action after Google redirect

### ISSUE THREAD

**Issue by prodonjs** [gsuitedevs/apps-script-oauth2#107]
I'm trying to set up a standalone Apps Script to list and process files from Google Cloud Storage. In trying to following the example from the README, I am unable to get my script to complete the redirect portion of the OAuth2 flow.

I am able to successfully see the Google authorization screen and click the Allow button, but when my browser redirects to the script's URL with the `/usercallback?state=` path and query string, I see the following message.

`Authorization is required to perform that action.`

I've dug into the ScriptApp documentation (https://developers.google.com/apps-script/reference/script/script-app#newStateToken()) and actually just tried testing hitting the callback URL without going through an actual authorization from Google and I still see the same issue. It leads me to believe that there is something wrong with the permissions on the Apps Script despite the fact that I am the owner of the script and there's a single sign-in active on my machine.

I'm curious as to whether this is specifically related to the library, or to my method of using a standalone Apps Script in general.

**Comment by prodonjs** [comment]
Also, just to followup, I receive the same error when attempting to use a script that is associated with a Sheet.

**Comment by pauladamgordon** [comment]
Getting the same issue - my OAuth2 flow for connecting scripts to an external service (that have been working without issue until today) are now failing with the `Authorization is required to perform that action.` message.

**Comment by erickoledadevrel** [comment]
Thanks for the reports. I haven't been able to reproduce this yet, so I'll need to do some digging. Are you by any chance logged into multiple Google accounts in your browser? Can you try using going through the OAuth flow in an incognito window?

**Comment by pauladamgordon** [comment]
I thought that initially as I was trying it with 3 different accounts logged in, but also getting it in incognito with a single account.

Thanks for looking into it!

**Comment by prodonjs** [comment]
Likewise, I'm having the same issue using a fresh login in Incognito mode.

**Comment by pauladamgordon** [comment]
For reference, I'm using it to access Buffer (https://buffer.com). I can get through to the Buffer authorisation URL, but then fails when coming back to the script to handle the callback.

**Comment by smaeda-ks** [comment]
@prodonjs @pauladamgordon 
Try adding scopes in your manifest file manually.

e.g.

```json
{  
   "timeZone":"Etc/GMT",
   "dependencies":{  

   },
   "exceptionLogging":"STACKDRIVER",
   "oauthScopes":[  
      "https://www.googleapis.com/auth/script.external_request",
      "https://www.googleapis.com/auth/script.scriptapp"
   ]
}
```

https://github.com/googlesamples/apps-script-oauth2#setup
https://developers.google.com/apps-script/concepts/scopes

**Comment by pauladamgordon** [comment]
Thanks, but these are already added to the manifest explicitly.

**Comment by smaeda-ks** [comment]
@pauladamgordon Understood. Actually, I also had the same problem yesterday and that did the trick in my case. Not quite sure what happened this time, but possibly something changed on Google side and we got some data inconsistency..?

**Comment by pauladamgordon** [comment]
Hmm, I've just tried things now and it seems to be working again...

**Comment by sp-philippe-oger** [comment]
I'm also having the same issue. Not sure what is going on. 
For previously authorised user, nothing changes, but the "authorise" flow leads to the same issue.

This happens in a script associated to a sheet, using the repo code as a library.

**Comment by erickoledadevrel** [comment]
It certainly seems like something is going on, but I have yet to experience this myself. For the folks still seeing this issue can you:

1. Verify that you are using the latest version of the library.
2. Try the [add-on sample](https://github.com/googlesamples/apps-script-oauth2/tree/master/samples/Add-on) and see if it also has the problem.

**Comment by oshliaer** [comment]
@erickoledadevrel , I've checked the sample. It works fine.

**Comment by machinefriendly** [comment]
@erickoledadevrel same issue was seen today with Facebook oauth setup which I did based on your code in readme, then I followed your suggestion to copy your sample FB code, it works now. The only difference between two versions of code is the part shown below, should that .setScope has conflict with the newest version of library? but looks that it's a change you did on v13. 
Moreover, I'm curious about how that scope selection works with newest version. Thanks.

```
      // Set the scopes to request (space-separated for Google services).
      .setScope('public_profile,user_likes,read_insights,manage_pages')

  // Below are Google-specific OAuth2 parameters.

      // Sets the login hint, which will prevent the account chooser screen
      // from being shown to users logged in with multiple accounts.
      .setParam('login_hint', Session.getActiveUser().getEmail())

      // Requests offline access.
      .setParam('access_type', 'offline')

      // Forces the approval prompt every time. This is useful for testing,
      // but not desirable in a production application.
      .setParam('approval_prompt', 'force');
```

**Comment by oshliaer** [comment]
@machinefriendly,

could you try `.setParam('approval_prompt', 'auto');`, please?

**Comment by machinefriendly** [comment]
@oshliaer  do you mean the below one? I tested it and it doesn't work, same warning message.
```
function getFbService() {
  return OAuth2.createService('Facebook')
  // Set the endpoint URLs.
  .setAuthorizationBaseUrl('https://www.facebook.com/dialog/oauth')
  .setTokenUrl('https://graph.facebook.com/v2.12/oauth/access_token')
  
  // Set the client ID and secret.
  .setClientId('2321321')
  .setClientSecret('fdsf342423')
  
  // Set the name of the callback function that should be invoked to complete
  // the OAuth flow.
  .setCallbackFunction('authCallback')
  
  // Set the property store where authorized tokens should be persisted.
  .setPropertyStore(PropertiesService.getScriptProperties())
  
     .setScope('public_profile,user_likes,read_insights,manage_pages')

  // Below are Google-specific OAuth2 parameters.

      // Sets the login hint, which will prevent the account chooser screen
      // from being shown to users logged in with multiple accounts.
      .setParam('login_hint', Session.getActiveUser().getEmail())

      // Requests offline access.
      .setParam('access_type', 'offline')

      // Forces the approval prompt every time. This is useful for testing,
      // but not desirable in a production application.
      .setParam('approval_prompt', 'auto');

}
```

**Comment by oshliaer** [comment]
@machinefriendly 

I can't reproduce the warning =( Perhaps the problem is not in the library but in the process of redirection and the callback function?

The following lines of code do not need
```js
     // Below are Google-specific OAuth2 parameters.

      // Sets the login hint, which will prevent the account chooser screen
      // from being shown to users logged in with multiple accounts.
      .setParam('login_hint', Session.getActiveUser().getEmail())

      // Requests offline access.
      .setParam('access_type', 'offline')

      // Forces the approval prompt every time. This is useful for testing,
      // but not desirable in a production application.
      .setParam('approval_prompt', 'force')
```

**Comment by erickoledadevrel** [comment]
Is anyone still able to reproduce this issue? I'm stumped as to what the problem could be and would love to see a repro case in action.

**Comment by tastanonur** [comment]
@erickoledadevrel 
I can still reproduce this issue. I have a script to set gmail signature. It works fine a gsuite account but it produce this issue for another gsuite account. I talked to Google API team, he says there is not any different your configurations and client ID rights. He recommend to talk with google script forums.

**Comment by erickoledadevrel** [comment]
@tastanonur Can you confirm that the problem still occurs if you are using an incognito window and only signed in with one Google account?

**Comment by tastanonur** [comment]
Yes the problem still occurs on incognito window and only signed in with one Google account. I tried again now.

**Comment by erickoledadevrel** [comment]
Are both accounts members of a G Suite domain? The same domain? Or are some of the accounts @gmail.com?

**Comment by tastanonur** [comment]
The account that works successfully is Gsuite Basic account. Other account that does not work  is Gsuite Business account. These are not same domain.

**Comment by erickoledadevrel** [comment]
Can you confirm that other accounts in the business domain are also failing with the same error? And that other accounts in the basic domain are succeeding with no error?

**Comment by gauravgupta123** [comment]
I am still facing the same issue and none of the above suggestions have worked so far.

**Comment by tastanonur** [comment]
@erickoledadevrel 

I tried some other accounts after your sent message. The problem does not depend on Gsuite account type like basic or Business.

**Comment by prodonjs** [comment]
I was able to successfully get the example to work!

For me, I had to explicitly set the oauthScopes property in the appsscript.json manifest file to the following:
"oauthScopes": [
    "https://www.googleapis.com/auth/script.external_request",
    "https://www.googleapis.com/auth/userinfo.email"
  ]

Adding those explicitly allowed the redirect function to be called which successfully completed the OAuth authorization.

**Comment by tastanonur** [comment]
Thank you very much @prodonjs.

I added "oauthScopes": in to the appsscript.json file. When i call the authorizationUrl, it displays a different error as "ReferenceError: "service" is not defined. (line 47, file "Code")". 

However it works successfully. I could call APIs this service.

**Comment by erickoledadevrel** [comment]
We suspect the problem has to do with `Session.getActiveUser()`. For those running into this issue, can you confirm that you are using this method in your script?

**Comment by oshliaer** [comment]
@erickoledadevrel 
I definitely did not use this method. I do not have the error in my tests.

**Comment by tastanonur** [comment]
@erickoledadevrel Yes i have _Session.getActiveUser().getEmail())_ method.

**Comment by gauravgupta123** [comment]
@erickoledadevrel Yes i have Session.getActiveUser().getEmail()) method.

**Comment by PhinkBig** [comment]
I also have a script using Session.getActiveUser() and am seeing this exact issue.

**Comment by erickoledadevrel** [comment]
The Apps Script team pushed out a new build that they believe should resolve this issue. Let me know if you see otherwise.

**Comment by jrichardsz** [comment]
September 2019, issue still continues.

My script is:

```
function showEmail() {
  var email = Session.getActiveUser().getEmail();
  return email;
}
```

And i have this error when I call or use this function:

![https://i.ibb.co/RbrvGHW/error.png](https://i.ibb.co/RbrvGHW/error.png)

**Comment by Edjaine** [comment]
I have similar error when I try read message from e-mail
![Erro Gmail](https://user-images.githubusercontent.com/25358334/89112189-805aa200-d435-11ea-9c9c-e9cfc7376a2a.png)
